# Generated by Django 2.2.6 on 2020-07-26 10:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image_description',
        ),
        migrations.AddField(
            model_name='postimage',
            name='sub_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
