# Generated by Django 2.2.6 on 2020-07-26 12:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200726_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
