# Generated by Django 2.2.6 on 2020-10-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton', '0002_auto_20201011_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyme',
            name='date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
